data:
  dataset_path: "chest_xray/dataset/"
  output_path: "Dataset-Final/"
  image_size: 150

training:
  batch_size: 32
  epochs: 30
  learning_rate: 0.001

augmentation:
  images_to_generate: 2000
